/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;

/**
 *
 * @author jonatanLara
 */
public class MainForm extends javax.swing.JFrame {
    //DECLARO MIS CONSTANTES
    public final int TAMANIO_PEQUENIO = 12;
    public final int TAMANIO_MEDIANO = 18;
    public final int TAMANIO_GRANDE = 24;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        fuentesList.setSelectedIndex(0);
        pequenioRadioButton.setSelected(true);
        menuItemPequenio.setSelected(true);
        
        menuItemNegrita.setSelected(false);
        menuItemCursiva.setSelected(false);
        
        setFuente();
    }
    public void setFuente(){
       // creo una instancia de la clase Font (necesito 3 parametros )
       String fuente = (String) fuentesList.getSelectedValue();
        //texto.setFont(new Font(fuente, Font.BOLD, 18));
        int estilo =Font.PLAIN;
        //checo si esta marcada (isSelected())
        //no se pude usar else porque cada uno de los checkbox son individuales
        if(negritasCheckBox.isSelected()==true){
            estilo = estilo + Font.BOLD;//ponte en negrita
        }
        if (cursivasCheckBox.isSelected()==true) {
            estilo = estilo + Font.ITALIC;
        }
        //texto.setFont(new Font(fuente, estilo, 18));
        //aqui si se puede poner un else porque los radio button noson independientes  
        int tamanio = TAMANIO_PEQUENIO;
        if (pequenioRadioButton.isSelected()==true){
            tamanio = TAMANIO_PEQUENIO;
        }else if( medianoRadioButton.isSelected()==true){
            tamanio = TAMANIO_MEDIANO;
        }else{
            tamanio = TAMANIO_GRANDE;
        }
        texto.setFont(new Font(fuente, estilo, tamanio));
    }
    
    private void cambiaNombreDeFuente(JMenuItem menuItem){
        String fuente = menuItem.getText();
        //menuItemArial nos devolvera el texto que tiene
        fuentesList.setSelectedValue(fuente, true);//true cuando esta seleccionado
        setFuente();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTamanio = new javax.swing.ButtonGroup();
        grupoMenuTamaño = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        texto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        negritasCheckBox = new javax.swing.JCheckBox();
        cursivasCheckBox = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        pequenioRadioButton = new javax.swing.JRadioButton();
        medianoRadioButton = new javax.swing.JRadioButton();
        grandeRadioButton = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fuentesList = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuItemAbrir = new javax.swing.JMenuItem();
        menuItemGuardar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemSalir = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        Jmenu2 = new javax.swing.JMenu();
        menuItemArial = new javax.swing.JMenuItem();
        menuItemTimesNewRoman = new javax.swing.JMenuItem();
        menuItemConsola = new javax.swing.JMenuItem();
        menuItemCalibri = new javax.swing.JMenuItem();
        menuItemComicSansMS = new javax.swing.JMenuItem();
        MenuItemLucida = new javax.swing.JMenuItem();
        menuItemVerdana = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemNegrita = new javax.swing.JCheckBoxMenuItem();
        menuItemCursiva = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItemPequenio = new javax.swing.JRadioButtonMenuItem();
        menuItemMediano = new javax.swing.JRadioButtonMenuItem();
        menuItemGrande = new javax.swing.JRadioButtonMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuItemColor = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuItemContenido = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuItemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto.setText("Tópicos Avanzandos de Programación");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Estilo"));

        negritasCheckBox.setText("Negritas");
        negritasCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negritasCheckBoxActionPerformed(evt);
            }
        });

        cursivasCheckBox.setText("Cursivas");
        cursivasCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursivasCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(negritasCheckBox)
                    .addComponent(cursivasCheckBox))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(negritasCheckBox)
                .addGap(18, 18, 18)
                .addComponent(cursivasCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tamaño"));

        grupoTamanio.add(pequenioRadioButton);
        pequenioRadioButton.setText("Pequeño");
        pequenioRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pequenioRadioButtonActionPerformed(evt);
            }
        });

        grupoTamanio.add(medianoRadioButton);
        medianoRadioButton.setText("Mediano");
        medianoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medianoRadioButtonActionPerformed(evt);
            }
        });

        grupoTamanio.add(grandeRadioButton);
        grandeRadioButton.setText("Grande");
        grandeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grandeRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pequenioRadioButton)
                    .addComponent(medianoRadioButton)
                    .addComponent(grandeRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pequenioRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(medianoRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(grandeRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Fuente"));

        fuentesList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Arial", "Consola", "Calibri", "Comic Sans MS", "Lucida", "Verdana", "Times New Roman", "Tahoma" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        fuentesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        fuentesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                fuentesListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(fuentesList);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        menuArchivo.setText("Archivo");

        menuItemAbrir.setText("Abrir...");
        menuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAbrirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemAbrir);

        menuItemGuardar.setText("Cambiar texto");
        menuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGuardarActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemGuardar);
        menuArchivo.add(jSeparator1);

        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemSalir);

        jMenuBar1.add(menuArchivo);

        menuEditar.setText("Editar");

        Jmenu2.setText("Fuente..");

        menuItemArial.setText("Arial");
        menuItemArial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemArialActionPerformed(evt);
            }
        });
        Jmenu2.add(menuItemArial);

        menuItemTimesNewRoman.setText("Time New Roman");
        menuItemTimesNewRoman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTimesNewRomanActionPerformed(evt);
            }
        });
        Jmenu2.add(menuItemTimesNewRoman);

        menuItemConsola.setText("Consola");
        menuItemConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsolaActionPerformed(evt);
            }
        });
        Jmenu2.add(menuItemConsola);

        menuItemCalibri.setText("Calibri");
        menuItemCalibri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCalibriActionPerformed(evt);
            }
        });
        Jmenu2.add(menuItemCalibri);

        menuItemComicSansMS.setText("Comic Sans MS");
        menuItemComicSansMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemComicSansMSActionPerformed(evt);
            }
        });
        Jmenu2.add(menuItemComicSansMS);

        MenuItemLucida.setText("Lucida");
        MenuItemLucida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemLucidaActionPerformed(evt);
            }
        });
        Jmenu2.add(MenuItemLucida);

        menuItemVerdana.setText("Verdana");
        menuItemVerdana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVerdanaActionPerformed(evt);
            }
        });
        Jmenu2.add(menuItemVerdana);

        menuEditar.add(Jmenu2);

        jMenu2.setText("Estilo");

        menuItemNegrita.setSelected(true);
        menuItemNegrita.setText("Negrita");
        menuItemNegrita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNegritaActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemNegrita);

        menuItemCursiva.setSelected(true);
        menuItemCursiva.setText("Cursiva");
        menuItemCursiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCursivaActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemCursiva);

        menuEditar.add(jMenu2);

        jMenu3.setText("Tamaño");

        grupoMenuTamaño.add(menuItemPequenio);
        menuItemPequenio.setText("Pequeño");
        menuItemPequenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPequenioActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemPequenio);

        grupoMenuTamaño.add(menuItemMediano);
        menuItemMediano.setSelected(true);
        menuItemMediano.setText("Mediano");
        menuItemMediano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMedianoActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemMediano);

        grupoMenuTamaño.add(menuItemGrande);
        menuItemGrande.setText("Grande");
        menuItemGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGrandeActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemGrande);

        menuEditar.add(jMenu3);
        menuEditar.add(jSeparator3);

        menuItemColor.setText("Color");
        menuItemColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemColorActionPerformed(evt);
            }
        });
        menuEditar.add(menuItemColor);

        jMenuBar1.add(menuEditar);

        menuAyuda.setText("Ayuda?");

        menuItemContenido.setText("Contenido de la Ayuda");
        menuAyuda.add(menuItemContenido);
        menuAyuda.add(jSeparator2);

        menuItemAcercaDe.setText("Acerca de ...");
        menuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(menuItemAcercaDe);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void negritasCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negritasCheckBoxActionPerformed
        //Lepregunto que si menuItemNegrita esta seleccionado
        menuItemNegrita.setSelected(negritasCheckBox.isSelected());
        setFuente();
    }//GEN-LAST:event_negritasCheckBoxActionPerformed

    private void cursivasCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursivasCheckBoxActionPerformed
        menuItemCursiva.setSelected(cursivasCheckBox.isSelected());
        setFuente();
    }//GEN-LAST:event_cursivasCheckBoxActionPerformed

    private void pequenioRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pequenioRadioButtonActionPerformed
        menuItemPequenio.setSelected(pequenioRadioButton.isSelected());
        setFuente();
    }//GEN-LAST:event_pequenioRadioButtonActionPerformed

    private void medianoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medianoRadioButtonActionPerformed
        menuItemMediano.setSelected(medianoRadioButton.isSelected());
        setFuente();
    }//GEN-LAST:event_medianoRadioButtonActionPerformed

    private void grandeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grandeRadioButtonActionPerformed
        menuItemGrande.setSelected(grandeRadioButton.isSelected());
        setFuente();
    }//GEN-LAST:event_grandeRadioButtonActionPerformed

    private void fuentesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_fuentesListValueChanged
        setFuente();
        // TODO add your handling code here:
    }//GEN-LAST:event_fuentesListValueChanged

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        // menu salir
        System.exit(0);
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void menuItemArialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemArialActionPerformed
        cambiaNombreDeFuente(menuItemArial);
    }//GEN-LAST:event_menuItemArialActionPerformed

    private void menuItemTimesNewRomanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTimesNewRomanActionPerformed
        // TODO add your handling code here:
        cambiaNombreDeFuente(menuItemTimesNewRoman);
    }//GEN-LAST:event_menuItemTimesNewRomanActionPerformed

    private void menuItemConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsolaActionPerformed
        // TODO add your handling code here:
        cambiaNombreDeFuente(menuItemConsola);
    }//GEN-LAST:event_menuItemConsolaActionPerformed

    private void menuItemCalibriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCalibriActionPerformed
        // TODO add your handling code here:
        cambiaNombreDeFuente(menuItemCalibri);
    }//GEN-LAST:event_menuItemCalibriActionPerformed

    private void menuItemComicSansMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemComicSansMSActionPerformed
        // TODO add your handling code here:
        cambiaNombreDeFuente(menuItemComicSansMS);
    }//GEN-LAST:event_menuItemComicSansMSActionPerformed

    private void MenuItemLucidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLucidaActionPerformed
        // TODO add your handling code here:
        cambiaNombreDeFuente(MenuItemLucida);
    }//GEN-LAST:event_MenuItemLucidaActionPerformed

    private void menuItemVerdanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVerdanaActionPerformed
        // TODO add your handling code here:
        cambiaNombreDeFuente(menuItemVerdana);
    }//GEN-LAST:event_menuItemVerdanaActionPerformed

    private void menuItemNegritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNegritaActionPerformed
        // le pregunto si esta seleccionado, me devolvera si esta seleccionado
        negritasCheckBox.setSelected(menuItemNegrita.isSelected());
        setFuente();
    }//GEN-LAST:event_menuItemNegritaActionPerformed

    private void menuItemCursivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCursivaActionPerformed
        // TODO add your handling code here:
        cursivasCheckBox.setSelected(menuItemCursiva.isSelected());
        setFuente();
    }//GEN-LAST:event_menuItemCursivaActionPerformed

    private void menuItemPequenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPequenioActionPerformed
       pequenioRadioButton.setSelected(menuItemPequenio.isSelected());
       setFuente();
    }//GEN-LAST:event_menuItemPequenioActionPerformed

    private void menuItemMedianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMedianoActionPerformed
        // TODO add your handling code here:
        medianoRadioButton.setSelected(menuItemMediano.isSelected());
        setFuente();
    }//GEN-LAST:event_menuItemMedianoActionPerformed

    private void menuItemGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGrandeActionPerformed
        // TODO add your handling code here:
        grandeRadioButton.setSelected(menuItemGrande.isSelected());
        setFuente();
    }//GEN-LAST:event_menuItemGrandeActionPerformed

    private void menuItemColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemColorActionPerformed
        /* setForeground letras(primer plano) , background fondo(segundo plano) */
       // texto.setForeground(queremos que nos aparesca un dialogo); creamos una instancia
        Color colorInicial = texto.getForeground();
        /*showDialog(rootPane, null, color); 
        muestra un dialogo de 3 parametros un this , un titulo , color inicial*/
        Color NuevoColor = JColorChooser.showDialog(this, "Cambiar el Color", colorInicial);
        if (NuevoColor !=null) {
            
            texto.setForeground(NuevoColor);
        }
        
        
    }//GEN-LAST:event_menuItemColorActionPerformed

    private void menuItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAbrirActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int resultado;
        /*.showOpenDialog(); no regresa que oprimio una tecla */
        resultado = fileChooser.showOpenDialog(this);
        /*.showSaveDialog(); guarda un archivo */
        /*.showDialog(); resive mas parametros */
    }//GEN-LAST:event_menuItemAbrirActionPerformed

    private void menuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAcercaDeActionPerformed
        // TODO add your handling code here:
        DialogoAcercaDe dialogo = new DialogoAcercaDe(this, true);
        dialogo.setVisible(true);
    }//GEN-LAST:event_menuItemAcercaDeActionPerformed

    private void menuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGuardarActionPerformed
        // TODO add your handling code here:
        DialogoCambiarTexto dialogo = new DialogoCambiarTexto(this, true);
      //  dialogo.setVisible(true);
        //creo la instancia le mando a llamar al metodo ShowDialog
        int res = dialogo.showDialog(this);
        if (res == DialogoCambiarTexto.OPCION_ACEPTAR) {
            //cambiamos el texto
           // System.out.println("Se oprimio el boton Aceptar");
            texto.setText(dialogo.getTexto());
        }
        /*else
        {System.out.println("se oprimio el boton cancelar");}*/
    }//GEN-LAST:event_menuItemGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Jmenu2;
    private javax.swing.JMenuItem MenuItemLucida;
    private javax.swing.JCheckBox cursivasCheckBox;
    private javax.swing.JList fuentesList;
    private javax.swing.JRadioButton grandeRadioButton;
    private javax.swing.ButtonGroup grupoMenuTamaño;
    private javax.swing.ButtonGroup grupoTamanio;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JRadioButton medianoRadioButton;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenuItem menuItemAbrir;
    private javax.swing.JMenuItem menuItemAcercaDe;
    private javax.swing.JMenuItem menuItemArial;
    private javax.swing.JMenuItem menuItemCalibri;
    private javax.swing.JMenuItem menuItemColor;
    private javax.swing.JMenuItem menuItemComicSansMS;
    private javax.swing.JMenuItem menuItemConsola;
    private javax.swing.JMenuItem menuItemContenido;
    private javax.swing.JCheckBoxMenuItem menuItemCursiva;
    private javax.swing.JRadioButtonMenuItem menuItemGrande;
    private javax.swing.JMenuItem menuItemGuardar;
    private javax.swing.JRadioButtonMenuItem menuItemMediano;
    private javax.swing.JCheckBoxMenuItem menuItemNegrita;
    private javax.swing.JRadioButtonMenuItem menuItemPequenio;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenuItem menuItemTimesNewRoman;
    private javax.swing.JMenuItem menuItemVerdana;
    private javax.swing.JCheckBox negritasCheckBox;
    private javax.swing.JRadioButton pequenioRadioButton;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
